### ISSUE TITLE
Missing required "platform-project-id" in setters.yaml

### ISSUE THREAD

**Issue by diviner524** [GoogleCloudPlatform/blueprints#135]
This issue appears in two different blueprints:

https://github.com/GoogleCloudPlatform/blueprints/blob/main/catalog/acm/setters.yaml

https://github.com/GoogleCloudPlatform/blueprints/blob/main/catalog/anthos-cluster/setters.yaml

In both cases, we have "platform-project-id" missing in setters.yaml. As a result if customers try to apply these two blueprints they may see failure because this value is not set.

**Comment by bharathkkb** [comment]
@kaariger can you PTAL? Lets remove platform-project-id if not needed as a setter.

**Comment by kaariger** [comment]
Fixing this. This breaks the attribution mainly and does not impact the blueprint itself.
