### ISSUE TITLE
Missing GCPEnforceNamingV2

### ISSUE THREAD

**Issue by hilliao** [GoogleCloudPlatform/blueprints#143]
`kubectl get constrainttemplates -A|grep GCPEnforceNamingV2` returns nothing. @morgante , can you push a commit to fix it? I discussed with Poonam and she investigated with me. The following code file's folder should have the constraint template.
https://github.com/GoogleCloudPlatform/blueprints/blob/2b8afca2ef0662cf5ea39c797832ac9c5ea67c7e/catalog/hierarchy/env-bu/policies/naming-constraint.yaml#L15

The same applies to other 3 folders at https://github.com/GoogleCloudPlatform/blueprints/tree/2b8afca2ef0662cf5ea39c797832ac9c5ea67c7e/catalog/hierarchy

**Comment by bharathkkb** [comment]
Hi @hilliao 
We have it centralized in the policies dir here 
https://github.com/GoogleCloudPlatform/blueprints/blob/main/catalog/landing-zone/policies/folder-naming-constraint-template.yaml

**Comment by morgante** [comment]
@hilliao How are you deploying? If you have followed the landing zone tutorial then the template should be in your repo already.

**Comment by hilliao** [comment]
[the tutorial](https://cloud.google.com/anthos-config-management/docs/tutorials/landing-zone#removing_constraints) said `Removing constraints`. I deleted the organization policies as well as the constraint template. The constraint template is the only template in the [policies folder](https://github.com/GoogleCloudPlatform/blueprints/tree/main/catalog/landing-zone/policies). The steps should tell customers to keep  folder-naming-constraint-template.yaml in the policies folder. otherwise, most customers would just delete the unwanted policies as well as the constraint template. Would it be a doc fix? I rather have a folder called constraintTemplates in [landing-zone](https://github.com/GoogleCloudPlatform/blueprints/tree/main/catalog/landing-zone).

**Comment by morgante** [comment]
The tutorial describes how to remove individual policies. We never encourage you to delete the entire folder.
