### ISSUE TITLE
Default branch is master in cloud source repo

### ISSUE THREAD

**Issue by hilliao** [GoogleCloudPlatform/blueprints#144]
Hi, @morgante , I realize that the steps would fail to create infra blueprints as cloud source repo has default branch of master. [Here](https://github.com/GoogleCloudPlatform/blueprints/compare/main...hilliao:patch-1)'s my fix. I talked to @markebalch  about it. The full story is in [the doc](https://docs.google.com/document/d/1N3ZMB2kLRSfeKwB_j-c85qCWkUzmTE7sDG42jxp31UI/edit#)

**Comment by morgante** [comment]
Unfortunately it is not that simple. The default branch for repos depends on *your* local Git config. It's likely that you are still using `master` as your default, but the new best practice is `main`.

It's been incredibly hard to reproducibly track down and fix.

**Comment by morgante** [comment]
This is how to change your default branch: https://superuser.com/questions/1419613/change-git-init-default-branch-name
