### ISSUE TITLE
Question about  kpt-set: ${projects-namespace} not specified in setters.yaml

### ISSUE THREAD

**Issue by hilliao** [GoogleCloudPlatform/blueprints#145]
I noticed that line at 
https://github.com/GoogleCloudPlatform/blueprints/blob/2b8afca2ef0662cf5ea39c797832ac9c5ea67c7e/catalog/project/project.yaml#L18 has `namespace: projects # kpt-set: ${projects-namespace}` but it's not defined in [setters.yaml](https://github.com/GoogleCloudPlatform/blueprints/blob/main/catalog/project/setters.yaml). By following the steps, the upper level folder would have [landing-zone/setters.yaml](https://github.com/GoogleCloudPlatform/blueprints/blob/main/catalog/landing-zone/setters.yaml) which also does not have projects-namespace defined. I checked the deployment repo and the final value is `namespace: projects`. Should @morgante  define projects-namespace in [project/setters.yaml](https://github.com/GoogleCloudPlatform/blueprints/blob/main/catalog/project/setters.yaml)?

**Comment by morgante** [comment]
If you are following the landing zone guide, it is fine to use the default value for the projects namespace (`projects`). That's why it's left out of the setters.
