### ISSUE TITLE
Attaching owner information to a resource created through blueprint

### ISSUE THREAD

**Issue by sarathmohan4** [GoogleCloudPlatform/blueprints#162]
As for resources directly created through GCP console, the owner info is available in audit logs through the "principalEmail" field

But for the resources created through Config controller, will have the primary service account email of the namespace as the principalEmail.

How can we attach an owner information (email) to a resource created through config controller. I believe labels cannot be used for that (as per https://cloud.google.com/resource-manager/docs/creating-managing-labels#common-uses) and also labels will not allow special characters as values. Is there any other ways or custom annotation we can add for owner email?

**Comment by morgante** [comment]
In general, it is discouraged to have a single individual responsible for resources. Instead, we recommend using labels for the team that owns the resource.

Since this isn't really related to blueprints, closing this issue.
