### ISSUE TITLE
hope to see ResourceManagerPolicy with condition of expression of resource.matchTag(...)

### ISSUE THREAD

**Issue by hilliao** [GoogleCloudPlatform/blueprints#163]
many healthcare clients would like to implement organization policies to conditionally restrict PHI data in the regions based on the project's tag: us or tag: eu at [policies](https://github.com/GoogleCloudPlatform/blueprints/tree/main/catalog/landing-zone/policies)
[The doc page](https://cloud.google.com/resource-manager/docs/organization-policy/tags-organization-policy#organization_policy_inheritance) does not provide a config connector method to create the conditional policy but the gcloud command method only. Is creating such sample policy in the landing zone folder in scope?

**Comment by morgante** [comment]
This is not currently supported by Config Controller: https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/621
