### ISSUE TITLE
cloud source repo defaults to master, not main

### ISSUE THREAD

**Issue by hilliao** [GoogleCloudPlatform/blueprints#193]
I followed [the instructions](https://cloud.google.com/anthos-config-management/docs/tutorials/landing-zone#save_the_blueprint_to_git) but the source-repo and deployment-repo still produced the master branch which cause the error in the log assuming landing-zone-dev-0 is the project ID:

> hydration-controller
Error in the git-sync container: {"Msg":"unexpected error syncing repo, will retry","Err":"Run(git clone -v --no-checkout -b main --depth 1 https://source.developers.google.com/p/landing-zone-dev-0/r/deployment-repo /repo/source): exit status 128: { stdout: \"\", stderr: \"Cloning into '/repo/source'...\\nPOST git-upload-pack (299 bytes)\\nwarning: Could not find remote branch main to clone.\\nfatal: Remote branch main not found in upstream origin\\n\" }","Args":{}}
> git-sync
"msg"="unexpected error syncing repo, will retry" "error"="Run(git clone -v --no-checkout -b main --depth 1 https://source.developers.google.com/p/landing-zone-dev-0/r/deployment-repo /repo/source): exit status 128: { stdout: "", stderr: "Cloning into '/repo/source'...\nPOST git-upload-pack (299 bytes)\nwarning: Could not find remote branch main to clone.\nfatal: Remote branch main not found in upstream origin\n" }"

Then I tried to `kubectl edit ConfigManagement -n config-management` per the following in the doc:

> Note: To use an alternate branch for Config Sync, you can specify the branch name using the syncBranch field in the ConfigManagement object followed by reapplying the blueprint.

Then the following error in the log happened:

 > manager 
 "msg"="error transforming manifest" "error"="setting spec.git requires setting spec.enableLegacyFields to true"  

Then I tried to change `branch: main` to `branch: master` at `kubectl edit RootSync -n config-management-system` but the changes were overwritten after a minute.

Finally, I `git checkout -b main` and `git push --set-upstream origin main` to create the master branch to resolve the initial error.

**Comment by kaariger** [comment]
@hilliao I was not able to reproduce this issue.

The Cloud Source Repository has the master branch set to begin with. However, the instructions ask that you update git to set the default branch to main. It is documented in step 4 in this [section](https://cloud.google.com/anthos-config-management/docs/tutorials/landing-zone#save_the_blueprint_to_git)

4. Set the default branch to `main`:

```
git config init.defaultBranch main
```

Did you follow that step? It should have created the main branch when you commit the changes in the next step.

**Comment by hilliao** [comment]
I follow similar steps to create a new cloud source repository and push a file. The git command `git config init.defaultBranch main` does not appear to be effective. See the screenshot in the cloud shell. I discovered the bug when I was executing the landing zone commands per [the section](https://cloud.google.com/anthos-config-management/docs/tutorials/landing-zone#save_the_blueprint_to_git) exactly as the doc stated on my Ubuntu 20.04 workstation. I just used cloud shell with similar commands to show it's not a landing zone specific bug but how git command works. The fix is easy: create a new branch `main` based on master then push. It will save customers many hours if the doc has the correct commands.
![image](https://user-images.githubusercontent.com/1208650/178377372-df6ff537-8159-4319-8ea5-37d7749ff08b.png)

**Comment by kaariger** [comment]
It seems this issue was [reported earlier](https://github.com/GoogleCloudPlatform/blueprints/issues/144) as well but was closed. It’s caused some the local configuration of the git client which can vary among users.

I will add instructions on creating a main branch in the [Troubleshooting](https://cloud.google.com/anthos-config-management/docs/tutorials/landing-zone#troubleshooting) section.

**Comment by hilliao** [comment]
That should be enough. I reported it earlier. I want to understand why the following is broken:

> Note: To use an alternate branch for Config Sync, you can specify the branch name using the syncBranch field in the ConfigManagement object followed by reapplying the blueprint.

See in my initial post where I mentioned it. It appears `kubectl edit ConfigManagement -n config-management` is not effective. Can you try to reproduce the error I reported in the initial post?

**Comment by kaariger** [comment]
@hilliao can you please try to the following steps instead of the one listed in [this section](https://cloud.google.com/anthos-config-management/docs/tutorials/landing-zone#save_the_blueprint_to_git) and see if these resolve the issue for you.

1. Set the default branch to `main`:
`git config --global init.defaultBranch main`

1. Check out the Git repository created by the blueprint:
`gcloud source repos clone source-repo`

1. Move the GitOps blueprint into your Git repository:
`mv gitops source-repo`

1. Open the Git repository:
`cd source-repo/`

1. Commit the blueprint to Git and push your changes:
```
git add gitops/
git commit -m "Add GitOps blueprint"
git push
```

**Comment by hilliao** [comment]
yes, the steps would create a local main branch to push in cloud shell but still creates the master branch on Ubuntu 20.04's git. I'd put a documentation note about checking a local main branch is created before `git push`.
Once you push the updated doc contents, the issue here can be closed.

**Comment by hilliao** [comment]
How about the syncbranch error in the original post? It appears to be impossible to change the branch from main to anything. I did not expect to see such error: `"msg"="error transforming manifest" "error"="setting spec.git requires setting spec.enableLegacyFields to true"`

**Comment by kaariger** [comment]
> How about the syncbranch error in the original post? It appears to be impossible to change the branch from main to anything. I did not expect to see such error: `"msg"="error transforming manifest" "error"="setting spec.git requires setting spec.enableLegacyFields to true"`

Editing the resource directly won't work. You will have to edit the yaml in the gitops blueprint and use `kpt` to apply the updated yaml.

**Comment by hilliao** [comment]
What's unclear to me is the instruction below:
`
Note: To use an alternate branch for Config Sync, you can specify the branch name using the syncBranch field in the ConfigManagement object followed by reapplying the blueprint.
`
![image](https://user-images.githubusercontent.com/1208650/180560408-5092f422-baeb-46b6-aabf-9620ea69ea64.png)

Which step should I execute?

1. change [the line in RootSync](https://github.com/GoogleCloudPlatform/blueprints/blob/1ac8e4930c9da45e80c622d4cbd681ee0a7c364d/catalog/gitops/configsync/rootsync.yaml#L24) from branch: main to branch: master 
2. add after [the line in ConfigManagement](https://github.com/GoogleCloudPlatform/blueprints/blob/1ac8e4930c9da45e80c622d4cbd681ee0a7c364d/catalog/gitops/configsync/config-management.yaml#L22) syncBranch: master

Per [the instructions](https://cloud.google.com/anthos-config-management/docs/how-to/installing-kubectl#configuring-config-management-operator) on how to configure the operator, I should configure RootSync which means 2) is correct and 1) is bad and will cause the error of `spec.enableLegacyFields` in my prior comment. Do you agree?
