### ISSUE TITLE
SA sync-krmapihost-config-controller-1 is more than 30 characters

### ISSUE THREAD

**Issue by hilliao** [GoogleCloudPlatform/blueprints#195]
The [following command](https://cloud.google.com/anthos-config-management/docs/tutorials/landing-zone?hl=en#verify_success) returns error
`kubectl get gcp -n config-control -o yaml   `
```
status:
    conditions:
    - lastTransitionTime: "2022-08-02T00:20:03Z"
      message: 'Update call failed: error applying desired state: summary: Error creating
        service account: googleapi: Error 400: The account ID "sync-krmapihost-config-controller-1"
        does not have a length between 6 and 30., badRequest'
      reason: UpdateFailed
      status: "False"
      type: Ready
    observedGeneration: 1

  status:
    conditions:
    - lastTransitionTime: "2022-08-02T00:20:03Z"
      message: 'Update call failed: error setting policy: error applying changes:
        summary: Error setting IAM policy for project "$PROJECT_ID": googleapi:
        Error 400: Service account sync-krmapihost-config-controller-1@landing-zone-$PROJECT_ID.iam.gserviceaccount.com
        does not exist., badRequest'
      reason: UpdateFailed
      status: "False"
      type: Ready
    observedGeneration: 1
```

Observed:
https://github.com/GoogleCloudPlatform/blueprints/blob/1ac8e4930c9da45e80c622d4cbd681ee0a7c364d/catalog/gitops/configsync/configsync-iam.yaml#L19 after `kfp fn render` produces a SA of length==35. GCP does not allow creating service account with name > 30. 
Fix: change from `sync-${cluster-name}` to  `sync-${sa-cluster-name}`
3 lines in configsync-iam.yaml. One of them is
```
  name: sync-krmapihost-config-controller-1 # kpt-set: sync-${sa-cluster-name}
```
1 line in rootsync.yaml:
```
    gcpServiceAccountEmail: sync-krmapihost-config-controller-1@$PROJECT_ID.iam.gserviceaccount.com # kpt-set: sync-${sa-cluster-name}@${project-id}.iam.gserviceaccount.com
```
add value in setters.yaml: `sa-cluster-name: krmapihost-cc-1`

**Comment by bharathkkb** [comment]
We could add a validator to prevent this cc @kaariger

**Comment by hilliao** [comment]
I missed the instruction of `echo ${CONFIG_CONTROLLER_NAME}` for cluster-name. config-controller-1 is the value, not krmapihost-config-controller-1
