### ISSUE TITLE
Unsupported ACM version 1.9.0 in GKEHubFeatureMembership

### ISSUE THREAD

**Issue by Yingxiao-ZHANG** [GoogleCloudPlatform/blueprints#196]
Failed to deploy the in GKEHubMembership/hub-membership in the blueprint [anthos-cluster/acm/config-mgmt-csr.yaml](https://github.com/GoogleCloudPlatform/blueprints/blob/main/catalog/anthos-cluster/acm/config-mgmt-csr.yaml). The error shows that acm v1.9.0 is not supported.

```
$ kubectl describe GKEHubFeatureMembership acm-membership-cluster-5 -n config-control
...
Status:
  Conditions:
    Last Transition Time:  2022-08-01T23:20:39Z
    Message:               Update call failed: error applying desired state: googleapi: Error 400: InvalidValueError for field version: unsupported ACM version 1.9.0 for Membership projects/817917611258/locations/global/memberships/hub-membership-cluster-5
    Reason:                UpdateFailed
    Status:                False
    Type:                  Ready
  Observed Generation:     1
```

Suggested fix:
configmanagement.version in [feedbackGKEHubFeatureMembership](https://cloud.google.com/config-connector/docs/reference/resource-docs/gkehub/gkehubfeaturemembership) is an optional field to set the ACM version. Defaults to the latest version. Hence, we should leave out the version and let it install the latest supported one.

follow-up questions:
1. Which component is no longer supported in v1.9.0?
2. Will the new ACM releases be compatible with the blueprint? Is it safe to use the latest version?
3. Is there notifications for the updates of the blueprints? We'd like to keep our code synced with the major releases.

**Comment by bharathkkb** [comment]
I think we should eliminate the field and setter. Users can do inplace edit if needed for explicit version. I will defer to @kaariger for confirmation. ACM releases should be compatible given unless a breaking change is identified in ACM and there is a major version bump.

For notifications you can use the built in [GitHub feature](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/about-notifications) or integrate with the GH releases API.
