### ISSUE TITLE
Validator functions should be moved to validators section in Kptfile

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleCloudPlatform/blueprints#37]
@morgante https://github.com/GoogleCloudPlatform/blueprints/blob/kpt-v1/catalog/landing-zone/Kptfile#L11

This function looks like a validator from its name. Please move it to `validators` section in Kptfile so that kpt can apply guard rails to not modify resources. Currently, `kpt fn render` leads to unnecessary diffs.

cc @mikebz @droot

**Comment by bharathkkb** [comment]
fixed by https://github.com/GoogleCloudPlatform/blueprints/pull/38
