### ISSUE TITLE
Comments should not rely on field order

### ISSUE THREAD

**Issue by phanimarupaka** [GoogleCloudPlatform/blueprints#39]
@morgante 

https://github.com/GoogleCloudPlatform/blueprints/blob/kpt-v1/catalog/gitops/setters.yaml#L6

In this file, the comment relies on the order of fields. You can do that with beta.2 of kpt but beta.1 of kpt may not retain the initial order of fields. Please audit other files and ensure comments are tied to particular field and not rely on the field order.

cc @mikebz @droot

**Comment by morgante** [comment]
Thanks, but I don't think it is reasonable to request us to not have ordered comments. I'm excited to hear this will be fixed in the next version of kpt though.
